server:
  port: 8081

spring:
  application:
    name: emp-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.emp: DEBUG